vich_uploader:
    db_driver: orm

    mappings:
        produit_image:
            uri_prefix: /img/products
            upload_destination: '%kernel.project_dir%/public/img/products'
            namer: Vich\UploaderBundle\Naming\OrignameNamer 
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true